export enum Currency {
    USD = "USD",
    EUR = "EUR",
    JPY = "JPY",
    GBP = "GBP",
    CNY = "CNY",
    AUD = "AUD",
    CAD = "CAD",
    CHF = "CHF",
    SGD = "SGD",
    SEK = "SEK",
    KRW = "KRW",
    NOK = "NOK",
    NZD = "NZD",
    INR = "INR",
    MXN = "MXN",
    TWD = "TWD",
    ZAR = "ZAR",
    BRL = "BRL",
    DKK = "DKK",
}