massive:
  base_url: "https://api.massive.com"
  run_during_market_close: true
  key_location: header
  key_param_name: "X-Api-Key"
  api_key_env_var: "MASSIVE_KEY"
  seconds_per_request: 12.00
  requests_per_min: 5
  asset_classes:
    stocks: true
  rest:
    batch_limits:
      stocks: 1
    credit_system: false

twelve_data:
  base_url: "https://api.twelvedata.com"
  run_during_market_close: true
  key_location: query
  key_param_name: "apikey"
  api_key_env_var: "TWELVEDATA_KEY"
  seconds_per_request: 29.25 # data updated once per day, so we can get unique data for (60*60*24)/29.25 = 2 953 ETFs
  requests_per_min: 8
  asset_classes:
    etfs: true
  rest:
    batch_limits:
      etfs: 1
    credit_system: true
    credit_cost_per_symbol: 1
    credits_replenishment:
      amount: 800
      period: day

vectrade:
  base_url: "https://api.vectrade.io"
  run_during_market_close: false # both stocks and options must only run during market open
  key_location: header
  key_param_name: "X-API-Key"
  api_key_env_var: "VECTRADE_KEY"
  seconds_per_request: 54.00 # with standard closing times, not considering holidays
  requests_per_min: 20
  requests_per_month: 10000
  asset_classes:
    stocks: true
    options: true
  rest:
    batch_limits:
      stocks: 50
      options: 1
    credit_system: false

eod_historical:
  base_url: "https://eodhd.com/api"
  run_during_market_close: false
  key_location: query
  key_param_name: "api_token"
  api_key_env_var: "EOD_KEY"
  seconds_per_request: 1700.00
  requests_per_min: 20
  asset_classes:
    stocks: false
    currencies: true
  rest:
    batch_limits:
      stocks: 1
      currencies: 1
    credit_system: false

finnhub: #currently broken
  base_url: "https://finnhub.io/api/v1"
  run_during_market_close: false #update when fixing
  key_location: query
  key_param_name: "token"
  api_key_env_var: "FINNHUB_KEY"
  seconds_per_request: 1
  requests_per_min: 60
  asset_classes:
    currencies: true
    crypto: true
  rest:
    batch_limits:
      quotes: 1
    credit_system: false

fcs:
  base_url: "https://api-v4.fcsapi.com/forex"
  run_during_market_close: false
  key_location: query
  key_param_name: "access_key"
  api_key_env_var: "FCS_KEY"
  seconds_per_request: 5356.80
  requests_per_min: 3
  requests_per_month: 500
  asset_classes:
    commodities: true
  rest:
    batch_limits:
      commodities: 300
    credit_system: true
    credit_cost_per_request: 1
    query_filters:
      type: "commodity"
    credits_replenishment:
      amount: 500
      period: month

coinmarketcap:
  base_url: "https://pro-api.coinmarketcap.com/v1"
  run_during_market_close: true
  key_location: header
  key_param_name: "X-CMC_PRO_API_KEY"
  api_key_env_var: "COINMARKETCAP_KEY"
  seconds_per_request: 178.56
  requests_per_min: 50
  requests_per_month: 15000
  asset_classes:
    crypto: true
  rest:
    batch_limits:
      crypto: 100
    credit_system: true
    credit_cost_per_symbol: 0.005
    credits_replenishment:
      amount: 15000
      period: month

coingecko:
  base_url: "https://api.coingecko.com/api/v3"
  run_during_market_close: true
  key_location: header
  key_param_name: "x_cg_demo_api_key"
  api_key_env_var: "COINGECKO_KEY"
  seconds_per_request: 267.84
  requests_per_min: 30
  requests_per_month: 10000
  asset_classes:
    crypto: true
  rest:
    batch_limits:
      crypto: 250
    credit_system: false

ticker_pools:
  stocks:
    - AAPL
    - MSFT
    - NVDA
    - AMD
  vectrade_stocks:
    - AAPL
    - TSLA
    - NVDA
  indices:
    - SPX
    - NDX
    - DJI
  futures:
    - ES=F
    - NQ=F
  currencies:
    - EUR/USD
    - USD/JPY
  crypto:
    - BTC
    - ETH
    - SOL
  commodities:
    - XAUUSD
    - SILVER
    - OSX
    - BRENT
    - NGAS