"""auto migration 2026-07-15T091626023Z

Revision ID: 002b810bfc5b
Revises: d21e79453c3a
Create Date: 2026-07-15 11:22:50.091161
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '002b810bfc5b'
down_revision = 'd21e79453c3a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategies',
    sa.Column('strat_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description_md', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('strat_id', name=op.f('strategies_pkey'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strategies')
    # ### end Alembic commands ###
