"""Updated_schema_changes

Revision ID: 2359f22cab05
Revises: 
Create Date: 2026-07-06 17:06:10.955998
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision = '2359f22cab05'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:

    op.execute("""
        DO $$
        DECLARE
            drop_stmt TEXT;
            type_drop_stmt TEXT;
            table_count INT;
        BEGIN
            SELECT COUNT(*) INTO table_count
            FROM information_schema.tables
            WHERE table_schema = 'public' AND table_name != 'alembic_version';

            IF table_count > 0 THEN
                RAISE NOTICE 'Pre-exsisting tables noticed killing them';

                SELECT 'DROP TABLE IF EXISTS ' || string_agg('"' || table_name || '"', ', ') || ' CASCADE;'
                INTO drop_stmt
                FROM information_schema.tables
                WHERE table_schema = 'public' AND table_name != 'alembic_version';

                IF drop_stmt IS NOT NULL THEN
                    EXECUTE drop_stmt;
                END IF;

                SELECT 'DROP TYPE IF EXISTS ' || string_agg('"' || typname || '"', ', ') || ' CASCADE;'
                INTO type_drop_stmt
                FROM pg_type t
                JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace
                WHERE n.nspname = 'public' AND t.typtype = 'e';

                IF type_drop_stmt IS NOT NULL THEN
                    EXECUTE type_drop_stmt;
                END IF;

                CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;

                RAISE NOTICE 'Schema construction beginning';

            ELSE
                RAISE NOTICE 'Schema empty going right to build';
            END IF;
        END $$;
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('asset_class', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('exchange', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.PrimaryKeyConstraint('asset_id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('currency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketcondition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('condition', sa.Enum('BULL', 'BEAR', 'RANGING', name='condition'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('dailyohlcv',
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('volume', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.asset_id'], ),
    sa.PrimaryKeyConstraint('asset_id', 'timestamp')
    )
    op.create_table('greeks',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('delta', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('gamma', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('theta', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('vega', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('rho', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('portfolio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cash_balance', sa.Numeric(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('realtimeticks',
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('volume', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.asset_id'], ),
    sa.PrimaryKeyConstraint('asset_id', 'timestamp')
    )
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('period_enum', sa.Enum('Daily', 'Weekly', name='period'), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_user_id'), 'report', ['user_id'], unique=False)
    op.create_table('stockasset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.asset_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('internationalaccount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['currency.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reportsection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('pct_change', sa.Float(), nullable=False),
    sa.Column('period_high', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('period_low', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reportsection_report_id'), 'reportsection', ['report_id'], unique=False)
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Enum('Sell', 'Buy', name='direction'), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price_at_execution', sa.Numeric(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['internationalaccount.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.asset_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_account_id'), 'transaction', ['account_id'], unique=False)
    op.create_index(op.f('ix_transaction_executed_at'), 'transaction', ['executed_at'], unique=False)

    op.execute("SELECT create_hypertable('realtimeticks', 'timestamp', chunk_time_interval => INTERVAL '1 day');")
    op.execute("SELECT create_hypertable('dailyohlcv', 'timestamp', chunk_time_interval => INTERVAL '1 year');")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_executed_at'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_account_id'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_index(op.f('ix_reportsection_report_id'), table_name='reportsection')
    op.drop_table('reportsection')
    op.drop_table('internationalaccount')
    op.drop_table('stockasset')
    op.drop_index(op.f('ix_report_user_id'), table_name='report')
    op.drop_table('report')
    op.drop_table('realtimeticks')
    op.drop_table('portfolio')
    op.drop_table('greeks')
    op.drop_table('dailyohlcv')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('marketcondition')
    op.drop_table('currency')
    op.drop_table('asset')
    # ### end Alembic commands ###
