"""add strategy detail fields

Revision ID: 2f1c70b453d1
Revises: 810f1603247e
Create Date: 2026-07-19 14:54:52.927793
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2f1c70b453d1'
down_revision = '810f1603247e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategies', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('strategies', sa.Column('level', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False))
    op.add_column('strategies', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False))
    op.add_column('strategies', sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('strategies', sa.Column('pros', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('strategies', sa.Column('cons', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('strategies', 'description_md')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategies', sa.Column('description_md', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('strategies', 'cons')
    op.drop_column('strategies', 'pros')
    op.drop_column('strategies', 'steps')
    op.drop_column('strategies', 'category')
    op.drop_column('strategies', 'level')
    op.drop_column('strategies', 'description')
    # ### end Alembic commands ###
