"""add experience_points and alo_rating

Revision ID: 3a9ef5d23c20
Revises: c362a6fedeef
Create Date: 2026-09-19 14:53:26.074494
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision = '3a9ef5d23c20'
down_revision = 'c362a6fedeef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('experience_points', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('elo_rating', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'elo_rating')
    op.drop_column('user', 'experience_points')
    # ### end Alembic commands ###
