"""Modified User table

Revision ID: 3b3dfc08f075
Revises: f1605719ec27
Create Date: 2026-09-19 15:46:10.976571
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3b3dfc08f075'
down_revision = 'eb0054a6c93b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('upgrades', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False))
    # ### end Alembic commands ###

        #Adding a trigger to add stuff to the users table that stuff being new technology
    op.execute("""
        CREATE OR REPLACE FUNCTION validate_user_tech_purchase()
        RETURNS TRIGGER AS $$
        
        DECLARE
            new_tech VARCHAR;
            tech_record RECORD;
            req_prereq VARCHAR;
            prereq_satisfied BOOLEAN;
            total_cost INT := 0;
        BEGIN
            IF OLD.upgrades IS NOT DISTINCT FROM NEW.upgrades THEN
                RETURN NEW;
            END IF;

            FOR new_tech IN
                SELECT unnest(NEW.upgrades)
                EXCEPT
                SELECT unnest(OLD.upgrades)

                LOOP

                    SELECT (node).cost AS cost, (node).prerequisites AS prerequisites
                    INTO tech_record
                    From techtree
                    WHERE (node).name = new_tech;

                    IF NOT FOUND THEN
                        RAISE EXCEPTION 'Technology does % the technology is not in the skill tree', new_tech;
                    END IF;

                    IF tech_record.prerequisites IS NOT NULL AND cardinality(tech_record.prerequisites) > 0 THEN
                        FOREACH req_prereq IN ARRAY tech_record.prerequisites LOOP
                            prereq_satisfied := req_prereq = ANY(OLD.upgrades);

                            IF NOT prereq_satisfied THEN
                                RAISE EXCEPTION 'Cannot unlock "%": Prerequisite "%" is not unlocked.', new_tech, req_prereq;
                            END IF;
                        END LOOP;

                    END IF;

                total_cost := total_cost + tech_record.cost;

            END LOOP;

            IF OLD.currency < total_cost THEN
                RAISE EXCEPTION 'Insufficient currency to purchase technology Required: %, Available: %.', total_cost, OLD.currency;
            END IF;

            NEW.currency := OLD.currency - total_cost;

            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;

        CREATE TRIGGER check_user_tech_purchase_before_update
        BEFORE UPDATE OF upgrades on "user"
        FOR EACH ROW
        EXECUTE FUNCTION validate_user_tech_purchase();
    """)


def downgrade() -> None:
    #Drop custom trigger
    op.execute("""
        DROP TRIGGER IF EXISTS check_user_tech_purchase_before_update ON "user";
        DROP FUNCTION IF EXISTS validate_user_tech_purchase();
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'upgrades')
    op.drop_column('user', 'elo')
    op.drop_column('user', 'currency')
    # ### end Alembic commands  ###
