"""Interval fixes

Revision ID: 49f6698cac4c
Revises: 2359f22cab05
Create Date: 2026-07-14 15:29:52.102266
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision = '49f6698cac4c'
down_revision = '2359f22cab05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('dailyohlcv_timestamp_idx'), table_name='dailyohlcv')
    op.drop_index(op.f('realtimeticks_timestamp_idx'), table_name='realtimeticks')
    # ### end Alembic commands ###

    #Interval adjustments
    op.execute("select set_chunk_time_interval('realtimeticks', INTERVAL '7 days');")
    op.execute("select set_chunk_time_interval('dailyohlcv', INTERVAL '1 year');")

    #make the CAGG view
    op.execute("""
        CREATE MATERIALIZED VIEW IF NOT EXISTS realtimeticks_hourly
        WITH (timescaledb.continuous) AS
        SELECT
            asset_id,
            time_bucket(INTERVAL '1 hour', "timestamp") AS bucket,
            MAX(price) AS high_price,
            MIN(price) AS low_price,
            SUM(volume) AS total_volume,
            COUNT(*) AS tick_count
        FROM realtimeticks
        GROUP BY asset_id, bucket
        WITH NO DATA;
    """)

    #Im going to forget if I dont write this down
    #start_offset we got back a week and look for data or what ever the interval is
    #end_offset dont look at the data from the last hour or what ever the interval is
    #schedule_interval Every 15 mins or what ever the interval is the process responsible for this will wake up and do the respective calculations
    op.execute("""
        SELECT add_continuous_aggregate_policy('realtimeticks_hourly',
            start_offset => INTERVAL '1 week', 
            end_offset => INTERVAl '1 hour',
            schedule_interval => INTERVAL '15 minutes'
        );
    """)


def downgrade() -> None:
    #can the refresh policy on going back
    op.execute("""
        SELECT remove_continuous_aggregate_policy('realtimeticks_hourly', if_exists => true);
    """)
    op.execute("DROP MATERIALIZED VIEW IF EXISTS realtimeticks_hourly CASCADE;")

    #Revert the chunk intervals back to how they use to be
    op.execute("SELECT set_chunk_time_interval('realtimeticks', INTERVAL '1 day');")
    op.execute("SELECT set_chunk_time_interval('dailyohlcv', INTERVAL '1 year');")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('realtimeticks_timestamp_idx'), 'realtimeticks', [sa.literal_column('timestamp DESC')], unique=False)
    op.create_index(op.f('dailyohlcv_timestamp_idx'), 'dailyohlcv', [sa.literal_column('timestamp DESC')], unique=False)
    # ### end Alembic commands ###
