"""Interval fixes

Revision ID: 49f6698cac4c
Revises: 2359f22cab05
Create Date: 2026-07-14 15:29:52.102266
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '49f6698cac4c'
down_revision = '2359f22cab05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('dailyohlcv_timestamp_idx'), table_name='dailyohlcv')
    # op.drop_index(op.f('realtimeticks_timestamp_idx'), table_name='realtimeticks')
    # ### end Alembic commands ###

    #op.execute("CREATE TYPE option_type AS ENUM ('CALL', 'PUT')")

    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'option_type') THEN
                CREATE TYPE option_type AS ENUM ('CALL', 'PUT');
            END IF;
        END $$;
    """)

    op.create_table(
        'options',
        sa.Column('asset_id', sa.Integer(), primary_key=True),
        sa.Column('option_type', sa.Enum('CALL', 'PUT', name='option_type', create_type=False), nullable=False),
        sa.Column('strike_price', sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column('expr_date', sa.DateTime(timezone=True), nullable=False),

        sa.Column('bid', sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column('last_price', sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column('volume', sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column('open_intrest', sa.Numeric(precision=18, scale=4), nullable=False),

        sa.Column('imp_vol', sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
        sa.Column('in_the_money', sa.Boolean(), server_default=sa.text('false'), nullable=False),

        sa.ForeignKeyConstraint(['asset_id'], ['asset.asset_id'], ondelete='CASCADE'),
    )

    #Interval adjustments
    op.execute("select set_chunk_time_interval('realtimeticks', INTERVAL '7 days');")
    op.execute("select set_chunk_time_interval('dailyohlcv', INTERVAL '1 year');")

    #make the CAGG view
    op.execute("""
        CREATE MATERIALIZED VIEW IF NOT EXISTS realtimeticks_hourly
        WITH (timescaledb.continuous) AS
        SELECT
            asset_id,
            time_bucket(INTERVAL '1 hour', "timestamp") AS bucket,
            MAX(price) AS high_price,
            MIN(price) AS low_price,
            SUM(volume) AS total_volume,
            COUNT(*) AS tick_count
        FROM realtimeticks
        GROUP BY asset_id, bucket
        WITH NO DATA;
    """)

    #Im going to forget if I dont write this down
    #start_offset we got back a week and look for data or what ever the interval is
    #end_offset dont look at the data from the last hour or what ever the interval is
    #schedule_interval Every 15 mins or what ever the interval is the process responsible for this will wake up and do the respective calculations
    op.execute("""
        SELECT add_continuous_aggregate_policy('realtimeticks_hourly',
            start_offset => INTERVAL '1 week', 
            end_offset => INTERVAl '1 hour',
            schedule_interval => INTERVAL '15 minutes'
        );
    """)

    op.execute("""
        CREATE MATERIALIZED VIEW IF NOT EXISTS ohlcv_1h
        WITH(timescaledb.continuous, timescaledb.materialized_only = false) AS
        SELECT
            time_bucket('1 hour', "timestamp") AS bucket_time,
            asset_id,
            first(open, "timestamp") AS open,
            max(high) AS high,
            min(low) AS low,
            last(close, "timestamp") AS close,
            sum(volume) AS volume
        From dailyohlcv
        GROUP BY bucket_time, asset_id
        WITH NO DATA;
    """)

    op.execute("""
        SELECT add_continuous_aggregate_policy('ohlcv_1h',
            start_offset => INTERVAL '1 month', 
            end_offset => INTERVAl '1 hour',
            schedule_interval => INTERVAL '1 hour'
        );
    """)


def downgrade() -> None:
    #can the refresh policy on going back
    op.execute("""
        SELECT remove_continuous_aggregate_policy('realtimeticks_hourly', if_exists => true);
    """)
    op.execute("""
        SELECT remove_continuous_aggregate_policy('ohlcv_1h', if_exists => true);
    """)
    op.execute("DROP MATERIALIZED VIEW IF EXISTS realtimeticks_hourly;")
    op.execute("DROP MATERIALIZED VIEW IF EXISTS ohlcv_1h;")

    #Revert the chunk intervals back to how they use to be
    op.execute("SELECT set_chunk_time_interval('realtimeticks', INTERVAL '1 day');")
    op.execute("SELECT set_chunk_time_interval('dailyohlcv', INTERVAL '1 year');")

    op.execute("DROP TABLE IF EXISTS options")
    op.execute("DROP TYPE IF EXISTS option_type")

    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index(op.f('realtimeticks_timestamp_idx'), 'realtimeticks', [sa.literal_column('timestamp DESC')], unique=False)
    # op.create_index(op.f('dailyohlcv_timestamp_idx'), 'dailyohlcv', [sa.literal_column('timestamp DESC')], unique=False)
    # ### end Alembic commands ###
