"""add report and report_section tables

Revision ID: 80437de1f01c
Revises: 22b90acef8af
Create Date: 2026-05-21 16:41:29.115798
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision = '80437de1f01c'
down_revision = '22b90acef8af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('period_enum', sa.Enum('Daily', 'Weekly', name='period'), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_user_id'), 'report', ['user_id'], unique=False)
    op.create_table('reportsection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('pct_change', sa.Float(), nullable=False),
    sa.Column('period_high', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('period_low', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reportsection_report_id'), 'reportsection', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reportsection_report_id'), table_name='reportsection')
    op.drop_table('reportsection')
    op.drop_index(op.f('ix_report_user_id'), table_name='report')
    op.drop_table('report')
    # ### end Alembic commands ###
