"""add actions log to practice simulation

Revision ID: 810f1603247e
Revises: 8f0fa351d638
Create Date: 2026-07-19 12:05:05.509256
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '810f1603247e'
down_revision = '8f0fa351d638'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('praticesimulation', sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('praticesimulation', 'actions')
    # ### end Alembic commands ###
