"""added last prices column

Revision ID: 8f0fa351d638
Revises: 626e02652203
Create Date: 2026-07-16 21:56:25.947274
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8f0fa351d638'
down_revision = '626e02652203'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('praticesimulation', sa.Column('last_prices', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('praticesimulation', 'last_prices')
    # ### end Alembic commands ###
