"""add reward allocation tracker and fix serverside defaults of elo and xp

Revision ID: b76649688f09
Revises: 3e9a5c7d1b28
Create Date: 2026-09-19 17:47:40.389253
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision = 'b76649688f09'
down_revision = '3e9a5c7d1b28'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('experience_points', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('user', sa.Column('elo_rating', sa.Integer(), server_default=sa.text('500'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'elo_rating')
    op.drop_column('user', 'experience_points')
    # ### end Alembic commands ###
