"""drop server defaults from multiplayer match seed columns

Revision ID: c362a6fedeef
Revises: 1526508f9ec5
Create Date: 2026-09-19 12:30:51.986339
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c362a6fedeef'
down_revision = '1526508f9ec5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('multiplayermatch', 'perturbation_seed',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('multiplayermatch', 'perturbation_version',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=False)
    op.alter_column('multiplayermatch', 'data_snapshot_id',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('multiplayermatch', 'data_snapshot_id',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'demo'::character varying"),
               existing_nullable=False)
    op.alter_column('multiplayermatch', 'perturbation_version',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'v1'::character varying"),
               existing_nullable=False)
    op.alter_column('multiplayermatch', 'perturbation_seed',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    # ### end Alembic commands ###
