"""auto migration 2026-07-12T233306340Z

Revision ID: d21e79453c3a
Revises: 2359f22cab05
Create Date: 2026-07-13 01:33:07.520065
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'd21e79453c3a'
down_revision = '2359f22cab05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('dailyohlcv_timestamp_idx'), table_name='dailyohlcv')
    op.drop_index(op.f('realtimeticks_timestamp_idx'), table_name='realtimeticks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('realtimeticks_timestamp_idx'), 'realtimeticks', [sa.literal_column('timestamp DESC')], unique=False)
    op.create_index(op.f('dailyohlcv_timestamp_idx'), 'dailyohlcv', [sa.literal_column('timestamp DESC')], unique=False)
    # ### end Alembic commands ###
