"""Created Tech Tree

Revision ID: f1605719ec27
Revises: a1b2c3d4e5f6
Create Date: 2026-09-19 13:49:53.664253
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.types import UserDefinedType
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f1605719ec27'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:

    #SQL alchemy is a asinine tool cant pick up UDT's lets mess with the autogenerated FILE
    # I will be leaving some of my own comments to demark what I added so I dont repeat not knowing what I touched beforehand

    # Make the UDT (Postgres is the best)
    op.execute("""
        CREATE TYPE "TechNode" AS (
            name VARCHAR,
            description VARCHAR,
            prerequisites VARCHAR[],
            unlocks VARCHAR[],
            cost INT
        );
    """)

    class TechNodeUDT(UserDefinedType):
        def get_col_spec(self, **kw):
            return '"TechNode"'

    #Make the table that houses the DAG (Directed Acyclic Graph)
    op.create_table(
        'techtree',
        sa.Column(
            'node_id',
            UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text('gen_random_uuid()')
        ),
        sa.Column('node', TechNodeUDT(), nullable=False)
    )

    #Add trigger for technodes
    # This will check if the previous tech exists or if your arnt making the price negative
    op.execute("""
        CREATE OR REPLACE FUNCTION validate_tech_node()
        RETURNS TRIGGER AS $$
        DECLARE
            prereq VARCHAR;
            prereq_exists BOOLEAN;
            has_cycle BOOLEAN;
            unlock_target VARCHAR;
            unlock_exists BOOLEAN;
        BEGIN
            IF (NEW.node).cost < 0 Then
                RAISE EXCEPTION 'There is no such thing as a free lunch. Techology cost cannot be negative: %', (NEW.node).cost;
            END IF;

            IF (NEW.node).prerequisites IS NOT NULL AND cardinality((NEW.node).prerequisites) > 0 THEN

              
                FOREACH prereq IN ARRAY (NEW.node).prerequisites LOOP
                    SELECT EXISTS (
                        SELECT 1 FROM techtree WHERE (node).name = prereq
                    ) INTO prereq_exists;

                    IF NOT prereq_exists THEN
                        RAISE EXCEPTION 'Prerequisite node "%" does not exist in the tech tree', prereq;
                    END IF;
                END LOOP;


                -- Due to the nature of DAG I need to prevent a cyclic dependency
                WITH RECURSIVE prereq_path AS (
                    SELECT (node).name AS current_node, (node).prerequisites AS req_prereqs
                    FROM techtree
                    WHERE (node).name = ANY((NEW.node).prerequisites)

                    UNION ALL

                    Select (t.node).name, (t.node).prerequisites
                    FROM techtree t
                    INNER JOIN prereq_path p ON (t.node).name = ANY(p.req_prereqs)
                )   
                SELECT EXISTS (
                    SELECT 1 FROM prereq_path WHERE current_node = (NEW.node).name
                ) INTO has_cycle;

                IF has_cycle THEN
                    RAISE EXCEPTION 'Circular dependency detected! Node "%" creates a loop in the tech tree. ', (NEW.node).name;
                END IF;

            END IF;

            IF (NEW.node).unlocks IS NOT NULL AND cardinality((NEW.node).unlocks) > 0 THEN
                FOREACH unlock_target IN ARRAY (NEW.node).unlocks LOOP
                    SELECT EXISTS (
                        SELECT 1 FROM techtree WHERE (node).name = unlock_target
                    ) INTO unlock_exists;

                    IF NOT unlock_exists THEN
                        RAISE EXCEPTION 'Unlock target node "%" does not exist in the tech tree', unlock_target;
                    END IF;
                END LOOP;
            END IF;

            RETURN NEW;
        END;

        $$ Language plpgsql;

        CREATE TRIGGER check_tech_node_before_save
        BEFORE INSERT OR UPDATE ON techtree
        FOR EACH ROW
        EXECUTE FUNCTION validate_tech_node();
    """)

    #Alembics auto generated code

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qtequestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.Enum('jargon', 'scenario', name='questiontype', create_type=False), nullable=False),
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('correct_answer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('correct_cash_delta_pct', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('incorrect_cash_delta_pct', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('multiplayermatch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('initial_balance', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'completed', 'abandoned', name='matchstatus'), nullable=False),
    sa.Column('player_one_id', sa.Integer(), nullable=False),
    sa.Column('player_two_id', sa.Integer(), nullable=False),
    sa.Column('winner_user_id', sa.Integer(), nullable=True),
    sa.Column('current_day_index', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_one_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['player_two_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], ),
    sa.ForeignKeyConstraint(['winner_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('multiplayerparticipant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('perturbation_seed', sa.Integer(), nullable=False),
    sa.Column('cash_balance', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('position_qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('final_balance', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('action_log', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('disconnected_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['multiplayermatch.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("""
        DO $$
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'optiontype') THEN 
                    CREATE TYPE optiontype AS ENUM ('CALL', 'PUT');
                END IF;
        END $$;
    """)
    op.alter_column('options', 'option_type',
               existing_type=postgresql.ENUM('CALL', 'PUT', name='option_type'),
               type_=sa.Enum('CALL', 'PUT', name='optiontype'),
               existing_nullable=False,
               postgresql_using='option_type::text::optiontype'),
    op.alter_column('options', 'in_the_money',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('options_timestamp_idx'), table_name='options')
    # ### end Alembic commands ###


def downgrade() -> None:
    #Drop the trigger functions
    op.execute("DROP TRIGGER IF EXISTS check_tech_node_before_save ON techtree; ")
    op.execute("DROP FUNCTION IF EXISTS validate_tech_node(); ")

    #Drop the UDT and DAG
    op.drop_table('techtree')
    op.execute('DROP TYPE IF EXISTS "TechNode" CASCADE; ')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('options_timestamp_idx'), 'options', [sa.literal_column('timestamp DESC')], unique=False)
    op.alter_column('options', 'in_the_money',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('options', 'option_type',
               existing_type=sa.Enum('CALL', 'PUT', name='optiontype'),
               type_=postgresql.ENUM('CALL', 'PUT', name='option_type'),
               existing_nullable=False,
               postgresql_using='option_type::text::option_type'),
    op.drop_table('multiplayerparticipant')
    op.drop_table('multiplayermatch')
    op.drop_table('scenario')
    op.drop_table('qtequestion')

    #To whom who made the 3 custome types in the afformentioned rows below
    #If you make a custom type YOU NEED TO WRITE THE EQIVALENT DROPS TO AVOID ISSUES
    #EVEN IF YOU MADE IT IN THE COLUMN YOU NEED TO WRITE THE DROPS YOURSELF. Do you even test downgrades?
    op.execute("DROP TYPE IF EXISTS questiontype CASCADE;")
    op.execute("DROP TYPE IF EXISTS matchstatus CASCADE;")
    op.execute("DROP TYPE IF EXISTS optiontype CASCADE;")
    # ### end Alembic commands ###
